### ISSUE TITLE
getChildren without supplying numChildren

### ISSUE THREAD

**Issue by lassemt** [ashleymarkfletcher/spark-ar-util#1]
Nice collection of helper functions, Ashley! 🤘🏼

I have a suggestion for a small update to the `getChildren` function. In the function now I believe it will throw an error to the console if the `numChildren` is too high, since the [SceneObjectBase](https://sparkar.facebook.com/ar-studio/learn/documentation/reference/classes/scenemodule.sceneobjectbase) class methods child and find throw an exception if the object isn't found. We can take advantage of this and "detect" whenever there are no more children to be found by using a while loop instead. 

It can look something like this:
```
export const getChildren = (parent, childPrefix) => {
  let children = [];
  let i = 0;
  let hasMatch = true;

  do {
    try {
      children.push(parent.child(childPrefix + i));
      i++;
    } catch(err) {
      hasMatch = false;
    }
  }
  while (hasMatch);

  return children;
}
```
This way you don't have to specify the number of children, so you don't have to change the code whenever you delete a child.

I haven't tested the code above, but it should work. I can make a PR if you like the idea 😊

**Comment by ashleymarkfletcher** [comment]
Thanks! 
This was just the first copy paste of all the code I've been reusing on projects haha.

Genius idea! I like it.

Definitely open a PR, I'm going to be pushing a few updates soon anyway.
